# name: Rust release build

# on:
#   push:
#     tags:
#       - 'release-*'
#     branches:
#       - 'release/**'
    
# env:
#   CARGO_TERM_COLOR: always

# jobs:
#   build-macos:
#     runs-on: macos-latest
#     steps:
#     - name: prepare rust 1.75
#       run: |
#         rustup install 1.75.0
#         rustup default 1.75.0
#         rustup target add aarch64-apple-darwin

#     - uses: actions/checkout@v3
#     - name: test-release
#       run: cargo test --release --verbose
        
#     # MacOS x86_64
#     - name: build-release x86_64
#       run: cargo build --release

#     - name: prepare-artifacts x86_64
#       run: |
#         # save version
#         PKG_VER=`cargo pkgid | cut -d# -f2 | cut -d: -f2`
#         echo "PKG_VER=${PKG_VER}" >> $GITHUB_ENV

#         # go to release folder
#         cd "${{ github.workspace }}/target/release/"

#         # save version and checksum files
#         echo $PKG_VER > VERSION
#         shasum -a 256 -b oxiflow > oxiflow.checksum

#         # change permission and pack it all
#         chmod +x oxiflow
#         tar -cvf "oxiflow-${PKG_VER}.tar" oxiflow oxiflow.checksum VERSION
    
#     - name: upload-artifacts
#       uses: actions/upload-artifact@v4
#       with:
#         name: oxiflow-${{ env.PKG_VER }}-mac-x86_64
#         path: "${{ github.workspace }}/target/release/oxiflow-${{ env.PKG_VER }}.tar"
#         overwrite: true
    
    
#     # MacOS arm64
#     - name: build-release arm64
#       run: cargo build --target aarch64-apple-darwin --release

#     - name: prepare-artifacts arm64
#       run: |
#         # save version
#         PKG_VER=`cargo pkgid | cut -d# -f2 | cut -d: -f2`

#         # go to release folder
#         cd "${{ github.workspace }}/target/aarch64-apple-darwin/release/"

#         # save version and checksum files
#         echo $PKG_VER > VERSION
#         shasum -a 256 -b oxiflow > oxiflow.checksum

#         # change permission and pack it all
#         chmod +x oxiflow
#         tar -cvf "oxiflow-${PKG_VER}.tar" oxiflow oxiflow.checksum VERSION
    
#     - name: upload-artifacts
#       uses: actions/upload-artifact@v4
#       with:
#         name: oxiflow-${{ env.PKG_VER }}-mac-arm64
#         path: "${{ github.workspace }}/target/aarch64-apple-darwin/release/oxiflow-${{ env.PKG_VER }}.tar"
  
  
#   build-linux:
#     runs-on: ubuntu-latest
#     steps:
#     - name: prepare rust 1.75
#       run: |
#         rustup install 1.75.0
#         rustup default 1.75.0

#     - uses: actions/checkout@v3
#     - name: test-release
#       run: cargo test --release --verbose
        
#     # Linux x86_64
#     - name: build-release x86_64
#       run: cargo build --release

#     - name: prepare-artifacts x86_64
#       run: |
#         # save version
#         PKG_VER=`cargo pkgid | cut -d# -f2 | cut -d: -f2`
#         echo "PKG_VER=${PKG_VER}" >> $GITHUB_ENV
#         echo "LIBC_VER=$(ldd --version | head -n1 | cut -d' ' -f5)" >> $GITHUB_ENV

#         # go to release folder
#         cd "${{ github.workspace }}/target/release/"

#         # save version and checksum files
#         echo $PKG_VER > VERSION
#         shasum -a 256 -b oxiflow > oxiflow.checksum

#         # change permission and pack it all
#         chmod +x oxiflow
#         tar -cvf "oxiflow-${PKG_VER}.tar" oxiflow oxiflow.checksum VERSION
    
#     - name: upload-artifacts
#       uses: actions/upload-artifact@v4
#       with:
#         name: oxiflow-${{ env.PKG_VER }}-linux-x86_64-libc-${{ env.LIBC_VER }}
#         path: "${{ github.workspace }}/target/release/oxiflow-${{ env.PKG_VER }}.tar"
#         overwrite: true
  
#   build-windows:
#     runs-on: windows-latest
#     steps:
#     - name: prepare rust 1.75
#       run: |
#         rustup install 1.75.0
#         rustup default 1.75.0

#     - uses: actions/checkout@v3
#     - name: test-release
#       run: cargo test --release --verbose
        
#     - name: build-release-win
#       run: cargo build --release

#     - name: prepare-artifacts
#       run: |
#         # save version
#         $env:PKG_VER = (cargo pkgid | ForEach-Object {$_.split("#")[1]})
#         echo "PKG_VER=$env:PKG_VER" >> $env:GITHUB_ENV

#         # go to release folder
#         cd "${{ github.workspace }}/target/release/"

#         # save version and checksum files
#         echo $env:PKG_VER > VERSION.txt
#         Get-FileHash -Algorithm SHA256 oxiflow.exe | Format-List > oxiflow.checksum

#         # move to final folder
#         mkdir artifacts
#         mv oxiflow.exe artifacts
#         mv oxiflow.checksum artifacts
#         mv VERSION.txt artifacts

#         # # change permission and pack it all
#         # tar -cvf "oxiflow-$env:PKG_VER.tar" oxiflow.exe oxiflow.checksum VERSION
    
#     - name: upload-artifacts
#       uses: actions/upload-artifact@v4
#       with:
#         name: oxiflow-${{ env.PKG_VER }}-windows-x86_64
#         path: "${{ github.workspace }}/target/release/artifacts/**"
#         overwrite: true
    