name: Rust release build

on:
  push:
    branches:
      - '*'
    
env:
  CARGO_TERM_COLOR: always

jobs:  
  build-windows:
    runs-on: ubuntu-20.04
    steps:
    - name: prepare rust 1.75
      run: |
        rustup install 1.75.0
        rustup default 1.75.0

    - uses: actions/checkout@v3
    - name: test-release
      run: cargo test --release --verbose
        
    - name: build-release-win
      run: cargo build --release

    - name: prepare-artifacts
      run: |
        # save version
        PKG_VER=`cargo pkgid | cut -d# -f2 | cut -d: -f2`
        echo "PKG_VER=${PKG_VER}" >> $GITHUB_ENV

        # go to release folder
        cd "${{ github.workspace }}/target/release/"

        # save version and checksum files
        echo $PKG_VER > VERSION
        shasum -a 1 -b oxiflow > oxiflow.checksum

        # change permission and pack it all
        chmod +x oxiflow
        tar -cvf "oxiflow-${PKG_VER}.tar" oxiflow oxiflow.checksum VERSION
    
    # - name: upload-artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: oxiflow-${{ env.PKG_VER }}-windows-x64
    #     path: "${{ github.workspace }}/target/release/oxiflow-${{ env.PKG_VER }}.tar"
    #     overwrite: true
    