name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: prepare rust 1.75
      run: |
        rustup install 1.75.0
        rustup default 1.75.0

    - uses: actions/checkout@v3
    - name: rest-release
      run: cargo test --verbose

    - name: build-release
      run: cargo build --release

    - name: prepare-artifacts
      run: |
        PKG_VER=`cargo pkgid | cut -d# -f2 | cut -d: -f2`
        echo "PKG_VER=${PKG_VER}" >> $GITHUB_ENV
        
        cd "${{ github.workspace }}/target/release/"
        shasum -a 1 -b oxiflow > oxiflow.checksum

        mkdir -p artifacts
        echo $PKG_VER > ./artifacts/VERSION
        mv oxiflow ./artifacts
        mv oxiflow.checksum ./artifacts
    
    - name: upload-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ env.PKG_VER }}
        path: "${{ github.workspace }}/target/release/artifacts/*"
        
