name: Rust release build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
    
env:
  CARGO_TERM_COLOR: always

jobs:  
  build-windows:
    runs-on: windows-latest
    steps:
    - name: prepare rust 1.75
      run: |
        rustup install 1.75.0
        rustup default 1.75.0

    - uses: actions/checkout@v3
    - name: test-release
      run: |
        cargo --version

    # - name: test-release
    #   run: cargo test --release --verbose
        
    - name: build-release-win
      run: cargo build --release

    - name: prepare-artifacts
      run: |
        # save version
        $env:PKG_VER= (cargo pkgid | ForEach-Object {$_.split("#")[1]})
        echo "PKG_VER=${PKG_VER}" >> $env:GITHUB_ENV

        # go to release folder
        cd "${{ github.workspace }}/target/release/"

        # save version and checksum files
        echo $PKG_VER > VERSION
        Get-FileHash -Algorithm SHA256 oxiflow.exe > oxiflow.checksum

        # change permission and pack it all
        tar -cvf "oxiflow-$env:PKG_VER.tar" oxiflow.exe oxiflow.checksum VERSION
    
    - name: upload-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: oxiflow-${{ env.PKG_VER }}-windows-x64
        path: "${{ github.workspace }}/target/release/oxiflow-${{ env.PKG_VER }}.tar"
        overwrite: true
    