name: Release build - Windows

on: push

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    steps:
    - name: prepare rust 1.75
      run: |
        rustup install 1.75.0
        rustup default 1.75.0

    - uses: actions/checkout@v4
    - name: test-release
      run: cargo test --release --verbose

    - name: build-release-win
      run: cargo build --release

    - name: prepare-artifacts
      env:
        PLATFORM: windows
        ARCH: x86_64

      run: |
        # setup env variables for build
        $env:PKG_VER=(cargo pkgid | ForEach-Object {$_.split("#")[1]})
        $env:TAR_FILE="oxiflow-${env:PKG_VER}-${env:PLATFORM}-${env:ARCH}.tar.gz"

        echo "PKG_VER=${env:PKG_VER}" >> $env:GITHUB_ENV
        echo "PKG_FILENAME=${env:TAR_FILE}" >> $env:GITHUB_ENV

        # go to release folder
        cd "${{ github.workspace }}/target/release/"

        # write version and checksum files
        echo $env:PKG_VER > VERSION.txt
        Get-FileHash -Algorithm SHA256 oxiflow.exe | Format-List > oxiflow.checksum

        # change permission and pack it all
        # no permision to change in windows
        tar -czvf"${env:TAR_FILE}" oxiflow.exe oxiflow.checksum VERSION.txt
    
    # - name: upload-artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ env.PKG_FILENAME }}
    #     path: "${{ github.workspace }}/target/release/${{ env.PKG_FILENAME }}"

    - name: create a release
      uses: softprops/action-gh-release@v2
      with:
        name: "v${{ env.PKG_VER }}"
        generate_release_notes: false
        make_latest: true
        body: "To be provided..."
        files: "./target/release/${{ env.PKG_FILENAME }}"
