name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: prepare rust 1.75
      run: |
        rustup install 1.75.0
        rustup default 1.75.0

    - uses: actions/checkout@v3
    - name: test-release
      run: cargo test --release --verbose

    - name: build-release
      run: cargo build --release

    - name: prepare-artifacts
      run: |
        # save version
        PKG_VER=`cargo pkgid | cut -d# -f2 | cut -d: -f2`
        echo "PKG_VER=${PKG_VER}" >> $GITHUB_ENV

        # go to release folder and create final folder
        cd "${{ github.workspace }}/target/release/"
        mkdir -p artifacts

        # save version and checksum files
        echo $PKG_VER > ./artifacts/VERSION
        shasum -a 1 -b oxiflow > ./artifacts/oxiflow.checksum

        # change permission and move binary
        chmod +x oxiflow
        mv oxiflow ./artifacts
    
    - name: upload-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ env.PKG_VER }}
        path: "${{ github.workspace }}/target/release/artifacts/*"
        overwrite: true
        
