name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
#   tests:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Rust 1.75.0
#       run: |
#         rm -fr /home/runner/.cargo/
#         curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
#         chmod +x rustup.sh
#         ./rustup.sh -y
#         rustup install 1.75.0
      
#     - name: Build
#       run: cargo build --verbose
#     - name: Run tests
#       run: cargo test --verbose
  
  build-macos:
    runs-on: macos-latest
    steps:
    - name: prepare rust 1.75
      run: |
        rustup install 1.75.0
        rustup default 1.75.0

    - uses: actions/checkout@v3
    - name: rest-release
      run: cargo test --verbose

    - name: build-release
      run: cargo build --release

    - name: prepare-artifacts
      run: |
        PKG_VER="0.1.3"
        mkdir -p "${{ github.workspace }}/target/release/"
        
        cd "${{ github.workspace }}/target/release/"
        # shasum -a 1 -b oxiflow > oxiflow.checksum
        # zip "release-$PKG_VER.zip" oxiflow.checksum oxiflow
        touch "release-$PKG_VER.zip"

        # ls -l "${{ github.workspace }}/target/release/release*.zip"
        ls -l ${{ github.workspace }}/target/release/
    
    - name: upload-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: "${{ github.workspace }}/target/release/release*.zip"
        
    
