name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rust 1.75.0
      run: |
        rm -fr /home/runner/.cargo/
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
        chmod +x rustup.sh
        ./rustup.sh -y
        rustup install 1.75.0
      
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
