name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
#   tests:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Rust 1.75.0
#       run: |
#         rm -fr /home/runner/.cargo/
#         curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
#         chmod +x rustup.sh
#         ./rustup.sh -y
#         rustup install 1.75.0
      
#     - name: Build
#       run: cargo build --verbose
#     - name: Run tests
#       run: cargo test --verbose
  
  build-macos:
    # needs: tests
    runs-on: macos-latest
    steps:
    # - name: prepare rust 1.75
    #   run: |
    #     rustup install 1.75.0
    #     rustup default 1.75.0

    - uses: actions/checkout@v3
    - name: build-release
      # run: cargo build --release
      run: pwd

    - name: build-release
      run: |
        PKG_VER="0.1.3"
        # PKG_VER=`cargo pkgid | cut -d# -f2 | cut -d: -f2` 
        # cd ./target/release/
        # shasum -a 1 -b oxiflow > oxiflow.checksum
        # zip "release-$PKG_VER.zip" oxiflow.checksum oxiflow
        touch "release-$PKG_VER.zip"

        ls -l "${{ github.workspace }}/target/release/release-*.zip"
        # ls -l ${{ github.workspace }}/target/release/
    
    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: releases
        path: "${{ github.workspace }}/target/release/release-*.zip"
        
    
