name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rust 1.75.0
      run: |
        ls -l /home/runner/.cargo/bin/
        rustup update 1.75.0
        which rustc
        rustc -V
        apt-cache search rust~i
        apt-cache policy rustc~i
        apt-get install rustc
      
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
